### ISSUE TITLE
Proceed to implement styling to the main.handlebars

### ISSUE THREAD

**Issue by wevexOP** [wevexOP/Cinder#38]

**Comment by wevexOP** [comment]
We will either be using bulma or some traditional CSS methods. Whatever works best for that super clean, apple/mobile friendly look.

**Comment by wevexOP** [comment]
This will also need to be done on the rest of the handlebars pages because they are essentially all the visual spaces for the application.

**Comment by studiomav** [comment]
We ended up going with bootstrap and it is set up to work globally across handlebars, marking as done
